### Create product.
POST http://localhost:3003/produto
Content-Type: application/json

{
    "name": "Placa de vídeo",
    "tags": "GTX,6gb,dual fan"
}

### Get Product
GET http://localhost:3003/produto/dual fan