### Create product.
POST http://localhost:3003/produto
Content-Type: application/json

{
    "name": "Camiseta regata",
    "tags": "personalizada,infantil"
}

### Get Product
GET http://localhost:3003/produto/caneca