### Criar novo usuário.
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Edwirges",
    "email": "edwirges@email.com",
    "password": "asdasd"
}

### Criar novo post.
POST http://localhost:3003/posts
Content-Type: application/json

{
    "authorId": "a63ff54d-98b6-48ed-868d-e62be83c7e24",
    "description": "Final de semana já era!",
    "photo": "https://picsum.photos/200/300",
    "type": "normal"    
}

### Buscar um post.
GET http://localhost:3003/posts/6ce59b4f-c59d-499d-94c6-540f39d850ca

### Criar uma amizade.
POST http://localhost:3003/friendship/3dcb546a-d517-4ac8-b701-2260b71aa3c8
Content-Type: application/json

{
    "receivingUserId": "a63ff54d-98b6-48ed-868d-e62be83c7e24"
}

### Deletar uma amizade.
DELETE http://localhost:3003/friendship/3dcb546a-d517-4ac8-b701-2260b71aa3c8/a63ff54d-98b6-48ed-868d-e62be83c7e24

### Ver todos os pots dos amigos do usuário.
GET http://localhost:3003/posts/c6c80397-4a2c-4a77-a7a1-5663992ecd73/feed/page?page=1

### Ver todos os post dos amigos do usuário por tipo.
GET http://localhost:3003/posts/c6c80397-4a2c-4a77-a7a1-5663992ecd73/feed/type?type=normal

### Curti post.
PUT http://localhost:3003/posts/liked/cde1f7bb-a6f9-46ec-9604-b5c8351fb0c1
Content-Type: application/json

{
    "liked": "true"
}