### Criar uma conta.
POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "lrds",
    "email": "lrds@live.com",
    "password": "#Asdasd1"
}
### Fazer login.
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "lrds@live.com",
    "password": "#Asdasd1"
}
